### ISSUE TITLE
Theme check REQUIRED  add_settings()  sanitization callback !!

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#11]
Theme check notice me 
<pre>
REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.
</pre>

Effected file is cs-framework\classes\customize.class.php code is below 
<pre>
 // add_setting
        $wp_customize->add_setting( $setting_name, wp_parse_args( $setting, $default_setting_args ) );
</pre>
I solve this by using array ,and REQUIRED notice gone .

<pre>
        // add_setting
        $wp_customize->add_setting( $setting_name, wp_parse_args( $setting, $default_setting_args ),array('sanitize_callback' => '__return_false',)  );

</pre>

**Comment by Codestar** [comment]
Hi,

Oh thanks for report. i will fix it ;)

**Comment by devariya** [comment]
You are welcome :+1:

**Comment by Codestar** [comment]
Hi,

I made an update for this notice.

```
// using sanitize callback inside add_setting function.
$wp_customize->add_setting( $setting_name,
  wp_parse_args( $setting, array(
      'type'              => 'option',
      'capability'        => 'edit_theme_options',
      'sanitize_callback' => 'cs_sanitize_clean',
    )
  )
);
```

Theme-Check only checking "sanitize_callback" text via regex. You can solve it with your method but it is not good, because only you can use add_setting function so:

http://codex.wordpress.org/Class_Reference/WP_Customize_Manager/add_setting
```
$wp_customize->add_setting($id, $args); // right
$wp_customize->add_setting($id, $args, $callback); // wrong
```

Now, i moved sanitize callback function inside $args. it is working now, re-download repo ;) or only update <a href="https://github.com/Codestar/codestar-framework/blob/master/classes/customize.class.php">customize.class.php</a>

**Comment by devariya** [comment]
Thanks man :+1:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by bulbulbigboss** [comment]
**devariya** is right guys can use devariya's solution . Thank you devariya
