### ISSUE TITLE
Group field not saving anymore

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#134]
Hi,

I develop a theme using CodeStar, One of my client tell me his group field is not saving anymore after creating 19 group field. I check it on my local server , working fine.

I think it's a server issue. Can you please tell me, how can I increase server limit for this. 

Thanks 
Imran Khan
CEO WPBean

**Comment by champsupertramp** [comment]
@wpbean 
did you try enabling the saving with ajax?

**Comment by wpbean** [comment]
@champsupertramp 
Yes I tried ajax save mode also, same problem.

**Comment by Codestar** [comment]
Hi,

I think problem is not only group field. Problem is server configure ```max_input_vars``` this limit is not imposed by Framework or any field. The limit is actually a server configuration issue. You can try this fixes ways:

```php
// php.ini (find it on hosting/ftp/cpanel files)
// and add this line.
max_input_vars = 10000;
```

```php
// go to wordpress .htaccess
// and add this line.
php_value max_input_vars 10000
```

```php
// go to wordpress wp-config.php
// and add this lines.
ini_set('max_input_vars', 10000);
define( 'WP_MEMORY_LIMIT', '96M' );
```

or search more on google :wink:

**Comment by wpbean** [comment]
Hi,
I do all the thing, and increase my max_input_vars to 10000, But it's giving me same result. 
If I remove all tables form database, it's work fine. But with my production site database it's not saving new field. It's just replace a previous one. 
Please give me any solution. 
Thanks

**Comment by Codestar** [comment]
Hi,

Ok let's check it. give me your production site wordpress admin informations also you can give me ftp for quicky try codes via codestarhelpme[at]gmail[dot]com

**Comment by devariya** [comment]
@Codestar any update about new version !!

**Comment by Codestar** [comment]
No any update.

**Comment by santiagointeractive** [comment]
In can confirm this issue. At a point I can't add any new fields. The last one I am creating removes the previous one. If I am deleting the previous one and add again another field this happens again with the one before that and so on. This has happened 3-4 times until now. I was able to fix it only by removing all that group entries and add them back.

This is very strange and can happen on groups with only 3 or 4 fields but nothing occurs on 20-30 fields group. This has nothing to do with the max_input_vars at all.

I think this has something to do with:

```
    echo $this->element_before();

    $last_id     = ( is_array( $this->value ) ) ? count( $this->value ) : 0;
    $acc_title   = ( isset( $this->field['accordion_title'] ) ) ? $this->field['accordion_title'] : __( 'Adding', CS_TEXTDOMAIN );
    $field_title = ( isset( $this->field['fields'][0]['title'] ) ) ? $this->field['fields'][0]['title'] : $this->field['fields'][1]['title'];
    $field_id    = ( isset( $this->field['fields'][0]['id'] ) ) ? $this->field['fields'][0]['id'] : $this->field['fields'][1]['id'];
    $search_id   = cs_array_search( $this->field['fields'], 'id', $acc_title );

    if( ! empty( $search_id ) ) {

      $acc_title = ( isset( $search_id[0]['title'] ) ) ? $search_id[0]['title'] : $acc_title;
      $field_id  = ( isset( $search_id[0]['id'] ) ) ? $search_id[0]['id'] : $field_id;

    }
```

But I haven't figure it out until now. Ithink somehow that search function is missing something. Is just a gues, maybe it's ok that part but is so damn strange...

**Comment by Codestar** [comment]
Hi,

Uh it is interesting. i am trying group options like this:

Group Count
![support_12-12-13](https://cloud.githubusercontent.com/assets/1313301/10217020/da73f492-6835-11e5-96cd-deeb203dfba3.png)

Group Inside Fields Count
![support_12-12-46](https://cloud.githubusercontent.com/assets/1313301/10217022/e9822f94-6835-11e5-8d36-1339199df16d.png)

It is saving normally.

**Comment by santiagointeractive** [comment]
Hi @Codestar,
How are you? Hope all is great :smile: 

For me it happened on a group with multiple options on a item (I have also textareas, select boxes, and switchers in there).
As I told before, this is not happening everywhere and there is no fixed limit of items when it does. Sometimes happened after 5 items, sometimes after 12 and in most cases doesn't happen at all but when it does I can fix it only by removing everything in that group and add them back again.

My other guess is that some special characters breaks the chain somehow, I cleaned up the fields for these but same issue is there. The only way I can fix it is to remove everything in that group and add them back again, then the problem is gone. So strange...

**Comment by Codestar** [comment]
Hi,

Oh thanks, i am fine. all is good. and you ? all is good ? hehe. :smile: hmm it is strange yes. hmm if you found a absolute bug share with me. i am ready for fix it. because i do not know where is the issue. maybe this is coming from server or php code ? i am not sure really :) let's wait a little. maybe we will learn absolute.

**Comment by Ansif** [comment]
Hi @wpbean, @SantiagoInteractive & @Codestar,

Any fixes for this issue?
