### ISSUE TITLE
Any field attribute for making the text field required? 

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#17]
Hi, I need to make a text field required. Didn't find any option for this in field attributes. Any other way to do this ?

Thanks

**Comment by santiagointeractive** [comment]
You can use <code>validate</code> for this.

<pre><code>array(
  'id'    => 'option_id', // this is must be unique
  'type'  => 'text',
  'title' => 'Text Field',
  'validate' => 'required',
),</code></pre>

You can use as well the following validation types: <code>numeric</code> - numbers only and <code>email</code> - email address validation, instead of <code>required</code> - any characters.
Hope it helps.

**Comment by wpbean** [comment]
@santiagointeractive  Hi, Tried validate as you show on your code, but not working for required.

Thanks

**Comment by santiagointeractive** [comment]
Can you paste your code here to see what's wrong with it?
I have just tested this a few minutes ago and it worked for me.

**Comment by wpbean** [comment]
Here my code.
<pre>
array(
              'id'          => 'plain_slider_btn_text',
              'type'        => 'text',
              'title'       => __('Button text','plain' ),
              'validate'    => 'required',
            ),
</pre>

**Comment by santiagointeractive** [comment]
If you are trying to use this on <code>shortcode.config</code> or <code>customize.config</code> won't work.

**Comment by wpbean** [comment]
I am trying to use these field for <code>metabox.config</code> , But not working.

**Comment by santiagointeractive** [comment]
Hmm... very strange. I can't replicate your problem. You should have a red text under that input saying "Fatal Error! This field is required!" after clicking Update button for your page.

**Comment by Codestar** [comment]
Hi,

Said as @santiagointeractive validate option available only for <code>framework.config</code> and <code>metabox.config</code> and i am seeing you are trying it for metabox. hmm it is interesting. take a look my setting and result below.

```
// metabox.config.php
array(
  'id'       => 'section_1_text',
  'type'     => 'text',
  'title'    => 'Text Field',
  'validate' => 'required',
),
```

![support_14-25-14](https://cloud.githubusercontent.com/assets/1313301/6092089/6099966e-aed5-11e4-8319-e95faf463df3.png)

It is working normally...

BTW, i did not add this option for <code>shortcodes.config</code> and <code>customize.config</code> because there is javascript operation. just write some custom javascript validator for this configs :) maybe i can add it in the future...

**Comment by wpbean** [comment]
Hi, @Codestar I am trying it inside a group. It's not working.

Here my code 
https://gist.github.com/wpbean/d02613acbb7b0e876749

Here my backend screenshot
<img src="http://puu.sh/fAYIj/7fd0fef755.png" />

**Comment by Codestar** [comment]
Hi,

Uh, inside group field option. why did not say group field first time :) hmm let me check it ;)

**Comment by Codestar** [comment]
Yes, you are right. hmm, i need to work on it. but i will add this feature in next updates ;) i noted this. btw, no worries about required field because we are giving this panel for clients. if a client do not write text it will not show. and all client will write text, trust me. Actually we need required file for payments and critical systems. i think here is not important required field for you.

I am using this framework for my themes i never used this option :smile:

**Comment by wpbean** [comment]
ok. Thanks @Codestar. You are really helpful. My English is also bad.

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by santiagointeractive** [comment]
I have a quick fix for this if anyone is interested.
Is not the most elegant way to do this but it does the task for now and you don't need to touch any core files of the framework.

**Step 1**
Create a new .js file. Let's call it <code>admin_extra-validation.js</code>
Put this code in there:

<pre><code>jQuery('form').submit(function(){
        var required_field = jQuery(".required-group-field");
        if ( required_field.val() == "" && required_field.is(':visible') ) {
           required_field.focus().after("Please enter a value!");
           return false;
        }
});
</code></pre>

**Step. 2**

Register <code>extra-validation.js</code> from functions.php of your theme to be added for backend only (wp-admin):
<pre><code>function extra_validation() {
    wp_enqueue_script( 'extra-validation-js', get_template_directory_uri(). '/js/admin_extra-validation.js', array( 'jquery' ), '', true );
}
add_action( 'admin_enqueue_scripts', 'extra_validation' );
</code></pre>

**Step 3**
Add a class attribute to every array you want, like this:

<pre><code>array(
      'id'         => 'field_id',
      'type'       => 'text',
      'title'      => 'Title',
      'class'      => 'required-group-field',
),
</code></pre>

**Comment by Codestar** [comment]
Yeah great solution :100: simple and easy :+1:

**Comment by gydoar** [comment]
Your solution not working in my Wordpress.
