### ISSUE TITLE
Not compatible with plugin MailOptin

### ISSUE THREAD

**Issue by LeninZapata** [Codestar/codestar-framework#18]
Hello, when your framework is installed in conjunction with this plugin is broken, the tabs do not work. Please review. https://wordpress.org/plugins/mailoptin/

**Comment by Codestar** [comment]
Hi,

Yes, There is a "#" hashtag control issue in location url. but this bug coming from plugin author code. Because the authour should be check the "#" hashtag for only their pages.

Let me explain it on an example.

1. Activate to MailOptin
2. Deactivate to Codestar Framework
3. Go to anywhere in admin panel. For eg. `Settings -> General`
4. Add a random hashtag like this.

`http://localhost/wp/wp-admin/options-general.php#something=hello`

5. Open the chrome console log.

You will see a js syntax error. Shortly, this plugin affect a lot of plugins. Not only my framework.

Regards, Codestar
