### ISSUE TITLE
It must include term meta

### ISSUE THREAD

**Issue by wowthemes** [Codestar/codestar-framework#181]
I really like this framework, missing thing is metabox in taxonomies. Can you please add this feature in this framework. 

The shortcode inserter feature is nice but it would be really awesome if you add feature like Shortcake https://wordpress.org/plugins/shortcode-ui/ , they stopped more development. And I hope you wouldn't stop updating this framework. 

I would really love to donate you :)

Thanks

**Comment by Codestar** [comment]
Hi,

Thanks for your opinions, Yes i will update this framework lifetime, surely. because i am a wordpress theme author as you know. I need to develop this framework as always.

And yes, I am thinking this feature for Shortcode UI. also we are discussion about this here #50 I will add it ASAP :wink: 

About your first question, I did not understand it well, can you explain it. you can use metabox option fields for any custom post type. hmm you mean for eg Posts -> "New Category" or "New Tag" pages taxonomies ?

Thanks for donate, i will be motivated :smile:
Regards, Codestar

**Comment by wowthemes** [comment]
Hi,

Yes, I am asking about Posts > New Category or New Tag or Custom Taxonomies.

and Thanks for considering my opinion :)

**Comment by Codestar** [comment]
Hi,

Hmm. Yes Some authors asking this feature. i will add it in next framework updates :wink: Noted this request.

**Comment by wowthemes** [comment]
If you want, I can contribute in the repo. Adding Shortcake and Taxonomy metaboxes :wink:

**Comment by Codestar** [comment]
Why not, you can fork repo and work on it. and report me when you finish it. if you write codes as lightweight we can merge surely :wink:
