### ISSUE TITLE
Did not work cs_get_option

### ISSUE THREAD

**Issue by partharoy** [Codestar/codestar-framework#208]
Hi I have recently setup your codestar framework. But I am unable to get the value. I am trying to upload a image and the option codes are
array(
      'id'      => 'site_logo',
      'type'    => 'image',
      'title'   => 'Logo Upload',
    )

After that I call the id with cs_get_option('site_logo') this function in header page. But It shows a number not the image. Also I am trying to use upload option but it shows only link of the picture?

Would you please tell me what happens?

**Comment by Ansif** [comment]
Hi,

For image type, that echo the image id instead of image URL.

Please try WordPress <a href="https://codex.wordpress.org/Function_Reference/wp_get_attachment_url" target="_blank">wp_get_attachment_url</a> function.

Output Should be : 
<pre>
$image_url = cs_get_option('site_logo');
echo wp_get_attachment_url($image_url);
</pre>

Enjoy! :+1:

**Comment by Codestar** [comment]
Hi, Yeah follow @Ansif answer.

**Comment by partharoy** [comment]
Hi Thank You @Codestar  and @Ansif
