### ISSUE TITLE
When will New and Updated version Comes?

### ISSUE THREAD

**Issue by partharoy** [Codestar/codestar-framework#220]
Hi,

I have updated files. Would you please tell me when will come your new updated version? And What feature you have added. And Why not you add this plugin in wordpress directory? Actually you need to marketing codestarframework. 

Thanks,
Partha Roy

**Comment by Codestar** [comment]
Hi,

I am planing to release a stable version after submit my new theme, because i am so busy now. I will add some new field and after i will release it :wink: 

About Plugin in WordPress Directory. I submited it already, but not accepted, because they saying "we will not accept any option framework" i do not know why :smile:  If you meet any wordpress reviewer, contact him about this ahah :+1:

**Comment by partharoy** [comment]
But there is many option framework in wordpress directory like redux, titan etc. As I know from wordpress 4 version it only allows customizer it follow its standards. That's why a plugin name kirki was born with the hand of redux framework developer.

**Comment by Codestar** [comment]
Hi,

Yes i said same thing, there is a lot of framework, they saying, "we accepted this frameworks before our new rule." i did not understand what is the problem. I will try it again. :wink:
