### ISSUE TITLE
Date timepicker and map

### ISSUE THREAD

**Issue by testphp24** [Codestar/codestar-framework#236]
Really Lovely framework for a WordPress developer, it'll be again benefit if you add the date and time picker, and map in the your existing plugin.
Thanks.

**Comment by Codestar** [comment]
Hi,

Yes this field on the way, it will come in next updates. :+1:

**Comment by ashawkat** [comment]
When the 1.1 version will release as it's really need the date field for metabox options. Can anyone let me know how to add a datepicker on codestar framework?

**Comment by NoahjChampion** [comment]
Hi @ashawkat . There won't be a version 1.1. @Codestar has made a version 2. It already has the date picker. 

It allows multiple instances and other features. 

Date picker screenshot...

<img src="https://cloud.githubusercontent.com/assets/1313301/17730359/11759580-6471-11e6-99bc-188313100cfb.gif">

Version 2 may release it before the end of the year. He will release it after his theme or right before, so maybe before the end of the year or earlier next year we expect. Screenshot...

![image](https://cloud.githubusercontent.com/assets/6123260/20647967/5b93294c-b468-11e6-9796-9377c126980a.png)

**Comment by baikaresandeep** [comment]
thanks for adding these fields

**Comment by stivoox** [comment]
How to get this field ??

**Comment by stivoox** [comment]
@baikaresandeep How to get this field ? I can't find how

**Comment by EnterpriseBranding** [comment]
Hi @stivoox 

This field is not available in this version. You will have to wait until version 2 is released. It is not yet.

You might try @ https://github.com/varunsridharan or @ https://github.com/varunsridharan/vsp-framework

**Comment by varunsridharan** [comment]
@EnterpriseBranding Thanks for sharing it. but 
https://github.com/varunsridharan/vsp-framework 
is a plugin framework / boilerplate.

**Comment by EnterpriseBranding** [comment]
Hey genius man @varunsridharan :D Yes. But I listed you as well because you had a pulled version of Codestar. And I couldn't remember if in older threads you mentioned adding this field to the pulled version? Wasn't sure, which is why I listed you, so they could search your repos. I couldn't so quickly find your pulled version of Codestar. Is it still available?

**Comment by varunsridharan** [comment]
@EnterpriseBranding Sorry i am not anything u said. !! I am nothing compared to you guys 😄 

Also. yes i have added it. and its still available.

**Comment by EnterpriseBranding** [comment]
Yes you are. I read your achievements. Never underestimate your yourself. Heroes look in the mirror everyday all around the world, some go be heroes and some don't. You do. ;) Always. 

I'm a hero now. I've been too busy working and building the best Wordpress theme of all time. Guaranteed. Because WE ARE heroes.

You can add your link to your repo then?

Since this thread is a bit old, and I know Codestar is busy, I think it would be good to add your link to other users will find for their need for now instead of keep asking. Then maybe Codestar can close comments on this and open comments when next version is released maybe. Those were my thoughts, for others.

**Comment by varunsridharan** [comment]
@EnterpriseBranding 
I have added a link back here https://github.com/varunsridharan/vsp-framework

**Comment by EnterpriseBranding** [comment]
Great! Thanks. #Salute
