### ISSUE TITLE
Dependency on Section ...

### ISSUE THREAD

**Issue by Tekanewa** [Codestar/codestar-framework#256]
While the dependencies work great on individual settings, I'm wondering whether it is possible to make a whole section dependent upon the value of a setting in another (prior) section? 

That would be easier and faster than assigning the dependency to each setting within that section and would have the additional benefit that the section tab would show/hide as well, which would look better, than having an empty tab.

**Comment by NoahjChampion** [comment]
@Tekanewa 
I saw your issue earlier, but wasn't sure how much it would be needed. But, since I just now moved from testing a settings page to testing those same settings in a metabox, I see the immediate need for it. 

Are you using a post metabox too, maybe in the same manner with quite a bit of options? 

Here's My Case: 
- My post metabox has quite a lot of options and I would like them or tabs related to ones not chosen by the user to not appear until the user actually enable that option, so that the metabox will save viewing space. [Advanced Custom Fields](http://www.advancedcustomfields.com/) offers this, so they must of have seen the need or had it requested as well at some point. 
- Because my first tab can take up quite a bit of space on the edit screen, for now I only can think of having an empty tab or "first tab" with minimal description text so when the edit screen first loads that tab with less information (taking up less space) will be visible first. 

But, @Codestar this also brings this question up which I searched and planned to ask about later. Thoughts on adding horizontal tabs? Plans to add? (I wish I could develop at this point because I would just add it and pull request. I just know how to tweak follow directions and help out in smaller parts right now) :(
- Horizontal Tabs - I saw the use for them in the Settings panel, but since the settings page is all dedicated to CF, that page can easily do without horizontal tabs. Since the post edit screen is dedicated to an unknown amount of metaboxes, admin menus, the post editor, page builders like Visual Composer, and other custom plugin metaboxes, reducing the view space on first load is needed. 
- Horizontal tabs can help with this, but sections as a dependency (tabs, I think Tekanew means in my language) would be best, depending on how advanced/option full the post metabox is. 

Sorry if my English is bad (not as clear), I'm English :)

**Comment by Codestar** [comment]
Hey guys, as you know "dependency system" is complex a little. only i added basic dependency rules for fields. if you need more detailed "dependency" write a little custom javascript. it will be easy. because i can not add all dependency conbinations. imagine there is no limit :smile: Use your own js code for custom dependencies.

**Comment by NoahjChampion** [comment]
@Codestar :) I'll try and ok.

**Comment by NoahjChampion** [comment]
@Tekanewa 

I just realized this, that 3 days after your question I found an already built in framework solution for this. 

And you easily update any framework config you have to this solution as well. 

It's simple. You just need to place your `'fields' => array()` within another field type called `'fieldset'`. This will group all your fields within the HTML `<fieldset></fieldset>` class. 

See an example below... 

```php
// Let's create a fieldset, grouping all our below fields so creating a dependency is simpler and easier to manage
array(
  // Group ALL our below fields within the html <fieldset></fieldset> class
  'type' => 'fieldset',
  'id' => 'optional_fieldset_id', // When using un_array true below, you don't need a fieldset id
  'un_array' => true, // Optionally make these fields un_array when saved so we can call them more easily with less code
  // Because our below fields are within this 'type' => 'fieldset' 
  //  we can use just one dependency for all our fields below instead of
  //  creating the same dependency for all our individual fields
  'dependency' => array('my_dependency', '==', 'true'),
  // Let's start our fields
  'fields' => array(
    // Select Field
    array(
      'type' => 'select',
      'id' => 'field_1',
      'options' => array(
        'option_1' => 'Option 1',
        'option_2' => 'Option 2',
        'option_3' => 'Option 3',
      ),
    ),
    // Select Field
    array(
      'type' => 'select',
      'id' => 'field_2',,
      'options' => array(
        'option_1' => 'Option 1',
        'option_2' => 'Option 2',
        'option_3' => 'Option 3',
      ),
    ),
  ),
),
```

You can seemy thread on this for more @ #262 or the the direct comment/example [here](https://github.com/Codestar/codestar-framework/issues/262#issuecomment-201815091).
