### ISSUE TITLE
Theme Options & Meta Box are getting resetted

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#293]
Hello,

I am not very sure for how to re-produce this but I am getting this problem with latest version.
I am developing a theme and I faced this problem 3 or 4 times in Theme Options and 1 time in Meta Boxes. The data is getting reset and I got default data.

Also I think this happens because the page was opened for a long time. So here is the process. I opened Theme Options page. I enabled ajax so the Save process works with Ajax and will not load all page data. I save it now. Than I save it again after approx 20 or 30 minute than it's getting reset. This is what I think and I may be wrong but this is what I feel.

Also, for Meta Boxes (when editing page), I edit a page. Than save it now. Than I keep it opened for 30 or 40 min. Than I got WP login popup. I login and I can edit the page. Than save the page now and all the data is reset. This is what I feel happening. I am not sure if this is the real steps to re-reproduce this.

Can anyone test this and make this clear.

**Comment by kwayyinfotech** [comment]
I found perfect way to re-produce this for Meta Boxes reset problem. Here are steps:

- Add a page with some texts in meta boxes.
- Save it.
- Than the page will be open for edit.
- Now wait for some time and the WordPress login popup box will open. It will take some minutes or hours too.
- Now login and save the page with new data.
- Now all Meta box data are reset.

This is happened just now so I provided steps.

**Comment by NoahjChampion** [comment]
Just guessing here but it sounds like that particular issue would be related to the auto saving of Wordpress and metaboxes in general and maybe not Codestar. Did you try with other post metabolites? 

Or it could be related to Codestar. 

But for the post metabox do you really think it's worth testing? As a developer I run into the automatic logout issue too, but that is because I am a developer testing things. I never run into this issue on a live site unless I am testing. None of my clients that I know have ever kept the window open so long that they have been automatically logged out, because they are active in that window frequently enough so they are not logged out, which is what WordPress expects and should be done. 

So do you think it is worth the time to test such an issue until it is reported more often? 

On another note... Or things to look at. 

Did you try only a text field? 

Maybe that data still holds correctly for radio buttons, selects, etc.? 

I'm thinking since maybe the auto draft feature of WordPress may not be picking that up for Codestar text areas, so after a logout it doesn't remember the data entered. 

You can also set a longer time out on your sites if you want. 

Last, but if this is happening on the Setting pages of CF too, then maybe it is a different issue with how CF holds data not respecting WordPress's auto logout feature. 

I will pay attention next time I get locked out in dev to add some feedback, but I don't think I had this issue before. Are you using the latest master version too?

**Comment by kwayyinfotech** [comment]
Hello,

Yes you are right about the wait time. That is practically not going to happen for a normal user. I am agree with you.

But I have two points that I want to discuss.

1. The first point is I am not sure if this is happening with that long time or anything else. It's resetted two times on my localhost. I am working with coding so I will keep tracking for proper ways to re-produce this.
2. Also the second point is, if the login session thing should ignore the current change and keep the last settings than it will be ok. But that's not happening. It's making reset. So the main concern is reset. If it's just not saving current settings that it will be ok.

Also we have different version of Codestar. One from http://codestarframework.com/ homepage with shows v1.0.1 currently. And the second is from Github MASTER from https://github.com/Codestar/codestar-framework page. So please guide me which package should I use. I am going to make my theme live soon.

**Comment by Codestar** [comment]
@kwayyinfotech you need to use latest release always. take a look here https://github.com/Codestar/codestar-framework/releases

Github MASTER codes changing always. you know it is developing :wink: or give me an idea, what can i do :smile:
