### ISSUE TITLE
Generate CSS file after saving Theme Options/Posts/Pages/CPT?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#307]
Hi Bro,

Can we able to generate css file of our dynamic settings changes?

I've seen WordPress [Filesystem_API](https://codex.wordpress.org/Filesystem_API) to take a advantage of that.

Some basic code is here : [Reference Blog](https://geek.hellyer.kiwi/2014/06/27/saving-css-files-uploads-folder/)

>
> <?php
>
> // Lets create some test CSS code
> $css = '/* Some test CSS */ body {background:red;}';
> 
> // Stash CSS in uploads directory
> require_once( ABSPATH . 'wp-admin/includes/file.php' ); // We will probably need to load this file
> global $wp_filesystem;
> $upload_dir = wp_upload_dir(); // Grab uploads folder array
> $dir = trailingslashit( $upload_dir['basedir'] ) . 'some-folder/'; // Set storage directory path
> 
> WP_Filesystem(); // Initial WP file system
> $wp_filesystem->mkdir( $dir ); // Make a new folder for storing our file
> $wp_filesystem->put_contents( $dir . 'style.css', $css, 0644 ); // Finally, store the file :)
> 
> ?>
>

Do you've any simple example for this solution?

This will reduce large line of css code and only loads page based css for better loading performance!

Thanks 👍

**Comment by Ansif** [comment]
Advice needed! 😉 
@Codestar @NoahjChampion @filipeleira @Codevz

**Comment by Codevz** [comment]
@Ansif I'm using it like this, but not tested it on online server.

```PHP
global $wp_filesystem;
$file = CD_DIR . '/css/custom.css'; // Dynamic file inside theme folder

if ( empty( $wp_filesystem ) ) {
	require_once( ABSPATH .'/wp-admin/includes/file.php' );
	WP_Filesystem();
}

if ( $wp_filesystem ) {
	$old = $wp_filesystem->get_contents( $file );
	if ( $old !== $css ) { // Check if options changed so update dynamic file
		$wp_filesystem->put_contents( $file, $css, FS_CHMOD_FILE );
	}
} else { // if wp_filesystem doesn't exist so echo inline styles
	echo '<style>' . $css . '</style>';
}
```

**Comment by Codestar** [comment]
Hi bro,

I am using custom.css idea in my Route Theme. My codes is this. You can get some ideas. 

```php
//
// set up cache folder
// -------------------
$upload_dir = wp_upload_dir();
$cache_name = 'some-folder';
$cache_dir  = trailingslashit( $upload_dir['basedir'] ) . $cache_name;
$cache_url  = trailingslashit( $upload_dir['baseurl'] ) . $cache_name;

defined( 'PREFIX_CACHE_DIR' ) or define( 'PREFIX_CACHE_DIR', $cache_dir );
defined( 'PREFIX_CACHE_URL' ) or define( 'PREFIX_CACHE_URL', $cache_url );

//
// Enqueue custom styles
// ---------------------
function prefix_wp_enqueue_styles() {


	if( ! is_dir( PREFIX_CACHE_DIR ) ) {

		if( ! function_exists( 'WP_Filesystem' ) ) {
  		require_once( ABSPATH . 'wp-admin/includes/file.php' );
		}
	
	  WP_Filesystem();

	  global $wp_filesystem;
	
		$wp_filesystem->mkdir( PREFIX_CACHE_DIR );

	}

	// 1. checking is cache folder writable
	// 2. if user in customizer passed custom.css for avoid conflicts
	if( is_writable( PREFIX_CACHE_DIR ) && ! isset( $_POST['wp_customize'] ) ) {

    $has_cached = get_option( 'prefix-has-cached' );

    if( ! $has_cached ) {
      prefix_cache_css_file();
    }

    // check for multisite
    global $blog_id;
    $is_multisite = ( is_multisite() ) ? '-'. $blog_id : '';

    wp_enqueue_style( 'prefix-cs-custom', PREFIX_CACHE_URL .'/custom-style'. $is_multisite .'.css', array(), null );

  } else {

  	add_action( 'wp_head', function(){ 	echo '<style>'. prefix_genearet_css() .'</style>'; }, 99 );

  }

}
add_action( 'wp_enqueue_scripts', 'prefix_wp_enqueue_styles' );

//
// Generate cache css file
// -----------------------
function prefix_cache_css_file() {

  if( is_multisite() ) {
    global $blog_id;
    $css_file = PREFIX_CACHE_DIR . '/custom-style-'. $blog_id .'.css';
  } else {
    $css_file = PREFIX_CACHE_DIR . '/custom-style.css';
  }

  $css  = "/**\n";
  $css .= " * Do not touch this file! This file created by PHP\n";
  $css .= " * Last modifiyed time: ". date( 'M d Y, h:s:i' ) ."\n";
  $css .= " */\n\n\n";
  $css .= prefix_genearet_css();

	if( ! function_exists( 'WP_Filesystem' ) ) {
		require_once( ABSPATH . 'wp-admin/includes/file.php' );
	}

  WP_Filesystem();

  global $wp_filesystem;

  if ( ! $wp_filesystem->put_contents( $css_file, $css, FS_CHMOD_FILE ) ) {
    update_option( 'prefix-has-cached', false );
  } else {
    update_option( 'prefix-has-cached', true );
  }

}

//
// Generate cache css
// -----------------------
function prefix_genearet_css() {

  $css  = '';

  // You can include a php file here. for eg:
  // ob_start();
  // include_once 'large-styles.php';
  // $output .= ob_get_clean();

  // now i am writing a simple thing
  $css .= 'body{';
  $css .= 'background-color:'. cs_get_option( 'text_1' ) .';';
  $css .= '}';

	return $css;

}

//
// Reseting cache for regenerate
// -----------------------
function prefix_reset_cache() {
	update_option( 'prefix-has-cached', false );
}
// update your classes/framework.class.php because this filter i added now.
add_action( 'cs_validate_save_after', 'prefix_reset_cache' );
// add_action( 'customize_save_after', 'prefix_reset_cache' );
```

I combine my code with your request and tested the code, it is working. But it is needed some improves. if you improve it, share with us.

[twentysixteen.zip](https://github.com/Codestar/codestar-framework/files/246748/twentysixteen.zip)

Btw, you can download live example :+1: 

@Ansif @Codevz @NoahjChampion @filipeleira

**Comment by Codevz** [comment]
@Codestar Thanks for sharing code :smiley:

**Comment by Codestar** [comment]
You're welcome @Codevz :smile: hehe

**Comment by Ansif** [comment]
@Codestar Thanks, Bro! You're Always, Awesome! 👍 

I've checked your everything is straightforward! 💯 

I've seen new action `cs_validate_save_after` do i need to use this new action after adding framework.class.php file or can i use existing action? `cs_validate_save` because you've changed that action name to `_after`

Then, `prefix_genearet_css` function, can i also include css file? Instead of php file? So, my multiple shortcode css files will load if that element is added.

Thanks, Again! 😉

**Comment by Codestar** [comment]
@Ansif You're welcome :+1: Thanks for nice words.

Yes this filter added https://github.com/Codestar/codestar-framework/commit/5b9f5475c37acb83ad5f512b36d4790b9ee1a5ac you can use it :wink: 

About `prefix_generate_css` yes why not, you can use include css file. try it :wink: Btw do not forget to add an option for disable/enable custom css. because in some servers WP_Filesystem do not working perfectly. Add an option and Avoid for users questions hahaha :smile:

**Comment by Ansif** [comment]
That's Awesome! 👍 

Sure, i'll add this enable/disable option. And thanks for sharing your experience with WP_Filesystem! 👍

**Comment by Codestar** [comment]
Np, Nice :+1:

**Comment by stefansicher** [comment]
Thanks a lot for this!

It would be nice if the time when the custom css file was last modified would be added to the file name to force browsers to load the new css file. (/wp-content/uploads/custom-css/custom-style.css?1139919766)

**Comment by NoahjChampion** [comment]
@stefansicher Good to see you! 

Yes, but the code/operation for this and that are both actually not part of the framework, since it falls outside of the scope of a 5 in 1 all framework, that focuses on giving the users fields, rather than raw code features. Hope that makes sense :)

If you still are looking into this, you can research it online like I did before seeing this post. I only tinkered with it. I didn't get it to work so I just ignored it to come back to it later, as the only articles I found were a little old. #Priorities 

Here are some references using the [filemtime();](http://php.net/manual/en/function.filemtime.php) function. 
@ [Link 1](https://www.mojowill.com/developer/get-your-wordpress-css-changes-noticed-immediately/)
@ [Link 2](https://css-tricks.com/can-we-prevent-css-caching/)

Or you can look in the repo or any plugin/theme that you find does this and probably search for the [filemtime();](http://php.net/manual/en/function.filemtime.php) function and/or code to see how they are doing it. :)

Hope that helps. Let me know. Thanks!

**Comment by stefansicher** [comment]
@NoahjChampion Thanks, I already looked into the filemtime function and tried to get it working but I'm not a php developer (I mostly do frontend and design) and couldn't get it to work in a reasonable amount of time.

**Comment by NoahjChampion** [comment]
@stefansicher 

Ok, thanks. Well I'll remember to post back when I do. 

I searched the repo and saw there was no plugin for this, so I already plan to release a plugin that could do this, which is probably better for most because the majority of those it would benefit (I think) aren't php developers. 

Sound good!!??
- Thanks for the update.

**Comment by stefansicher** [comment]
@NoahjChampion Thank you! I don't know if a plugin would be the best solution for this, imho this functionality should sit next to the customizer.php in the theme directory. But in any case, thanks for your quick replies.

**Comment by NoahjChampion** [comment]
@stefansicher I agree, if anything, but it will be an option for my theme and since the coding will be done, thought to release it as a plugin.

Giving that I'm not going to try to push this to the core, the "next" best solution, I think would be a plugin. I may not know that I think of it. In most cases, the caching plugin being used should offer this. So I'm not really sure the demand for it when users are using caching anyway. 

My caching plugin does this, for example.

Initially I was just thinking for my dev time and other devs using my theme where they wouldn't have to clear the browser cache every time they changed a file. The latest edit would automatically show for them :) 

We'll see. I can post back either way, at least for anyone else who might want to know. 

Thanks again and you're welcome! #Peace

**Comment by BrooonS** [comment]
@stefansicher Maybe you add rand()?
`wp_enqueue_style( 'custom-styles', PREFIX_CACHE_URL . '/custom-style' . $is_multisite . '.css', array(), rand(0, 100000), null );`
