### ISSUE TITLE
PHP date on select field

### ISSUE THREAD

**Issue by filipeleira** [Codestar/codestar-framework#318]
Hi! 😄 

I have this metabox field, and I want to show the current day by default. The following code works only when isn't inside a fieldset. When I put inside a fieldset, it shows the wrong date. 😨 

> array(
>     'id'             => 'info_date',
>     'type'           => 'select',
>     'options'        => array(
>         01 => '01', 02 => '02', 03 => '03', 04 => '04', 05 => '05', 06 => '06', 07 => '07', 08 => '08', 09 => '09', 10 => '10', 11 => '11', 12 => '12', 13 => '13', 14 => '14', 15 => '15', 16 => '16', 17 => '17', 18 => '18', 19 => '19', 20 => '20', 21 => '21', 22 => '22', 23 => '23', 24 => '24', 25 => '25', 26 => '26', 27 => '27', 28 => '28', 29 => '29', 30 => '30', 31 => '31'
>     ),
>     'default'       => date('d'),
> ),

How can I fix this? I need that fieldset to group date, month and year, cause we don't have a date picker field 😢 

Thank you!

**Comment by Codevz** [comment]
Nice idea, try this: https://codex.wordpress.org/Function_Reference/current_time

`'default' => current_time('d'),`

If still didn't works, so i think problem is fieldset because switcher default also not works for me.

**Comment by Codestar** [comment]
Hey @filipeleira 

Ups yes, i missed set for default value. now i made a minor update for fieldset.php take a look last commit https://github.com/Codestar/codestar-framework/commit/e24f5ac301006f1d7fe5b508a155205bec157edb only update `fields/fieldset/fieldset.php` file.

About config array. I advise this config array.

```php
array(
  'id'      => 'info_date',
  'type'    => 'select',
  'options' => array(
    '01' => '01',
    '02' => '02',
    '03' => '03',
    '04' => '04',
    '05' => '05',
    '06' => '06',
    '07' => '07',
    '08' => '08',
    '09' => '09',
    '10' => '10',
  ),
  'default' => current_time('d'),
),
```

because `01` vs `'01'` if you using without quotes. `03` will return `3` only add quotes for all.

Also i advise `current_time( 'd' )` as said @Codevz 

Yeah, try and report us :+1:
