### ISSUE TITLE
cs_set_icons() function ajax problem

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#320]
Hi @codestar.
I think there is a problem about cs_set_icons() function.
I installed suvcesfully codestar and https://github.com/dtbaker/envato-wp-theme-setup-wizard/ together. When I deactivate codestar there is no problem. But when activated codestar on setup wizard I see the "Search a Icon" and shortcode selectbox of codestar. I really like codestar but this issue made me mad. 
Thanks for your efforts.

**Comment by Codestar** [comment]
Hi @cansanet 

I am including `cs_set_icons` in `admin_footer` action. and this icon selectbox hidding automatically. for eg. html output is starting like this:

```html
<div id="cs-icon-dialog" class="cs-dialog".....
```

and `.cs-dialog` style is `display: none` default. how you can see it? it is interesting really. can you check your page source for `cs-framework.css` file is including ?

**Comment by Codestar** [comment]
Hi again,

I checked dtbaker's setup wizard codes. and there is missing `admin_enqueue_scripts` action in header. take a look here https://github.com/dtbaker/envato-wp-theme-setup-wizard/blob/master/envato_setup/envato_setup.php#L401 see line 401 and add this code 

```
<?php do_action( 'admin_enqueue_scripts' ); ?>
```

Because i am using `admin_enqueue_scripts` for load script and styles. when you add it, it will work normally.

**Comment by cansanet** [comment]
Thank you @Codestar, The issue is fixed

**Comment by Codestar** [comment]
You're welcome :+1:
