### ISSUE TITLE
One click demo import

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#324]
Hi @codestar,
Do you think including a one click demo importer to this package as redux framework does. I tried a few plugins and some classes for this purpose but I coludnt find one which has the capability of serving more than one demo. If you think let me share my thougts else I will try to do another way for only demo import. Still codestarframework is best option panel for me. 
Thanks for efforts

**Comment by NoahjChampion** [comment]
@cansanet 

Check out @ [DT Demo Importer](https://github.com/AminulBD/dt-demo-importer)

And threads...

#229 
#87 
#320

**Comment by Codestar** [comment]
Yes as said @NoahjChampion i advise [DT Demo Importer](https://github.com/AminulBD/dt-demo-importer) by @AminulBD

Actually one click importer is a custom thing. Codestar framework have a basic import/export option. you can use this option field for your custom one click importer.

Shortly i mean, you need to create your own custom importer, because you know there is a lot of things, menus, widgets, options, revolution slider or another sliders and more. best way is create own importer.

:+1:

**Comment by cansanet** [comment]
I tried DT demo importer and had some errors. Ok I will try again this one

**Comment by cansanet** [comment]
Do you have any idea about this problem that I asked on https://github.com/AminulBD/dt-demo-importer/issues/5

I am asking you because it is related to codestar-framework.

Thank you

**Comment by NoahjChampion** [comment]
@cansanet 

You can mention it @AminulBD about a function like this or change it yourself, mentioned in #308   in [THIS COMMENT](https://github.com/Codestar/codestar-framework/issues/308#issuecomment-217632308)

```php
// Codevz's example
function is_cs_framework_active() {
  return ( function_exists( 'cs_get_option' ) ) ? true : false;
}

if( is_cs_framework_active() ) {
// do stuff
}
// Another example
function is_cs_framework_active() {
  return ( defined( 'CS_VERSION' ) ) ? true : false;
}

if( is_cs_framework_active() ) {
// do stuff
}
```

Tag: https://github.com/AminulBD/dt-demo-importer/issues/5

I like this method best so far because if it changes, the code only needs to be updated in one place.

Does that help?

**Comment by cansanet** [comment]
Thank you @NoahjChampion, I will try this

**Comment by cansanet** [comment]
Now I deleted that line, still it works. I think that line has no usage in plugin.

**Comment by NoahjChampion** [comment]
@cansanet maybe so? I'm not sure. I haven't set up demo import features yet. I'll remember to check it when I do. 

@Codestar

**Comment by ashawkat** [comment]
Well codestar has really very low support in case of redux & other frameworks. I love codestar but it seems they're really slow in terms of update in features. Don't know why but it's really a good framework for meta & options. It's been 2017 still I'm not seeing the latest version of codestar.

**Comment by Codestar** [comment]
Sorry for about support, I have not free-time for support. Redux have a team for core development. But i am alone. single worker :-)

It is a open-source script, you need to develop it by yourself. I am working full-time for themeforest for continue life.

**Comment by ashawkat** [comment]
I think you should at least try to release the v 1.1 with the features that some have merged or basic demo importer etc. Just the basic features so that in future people will try to contribute. it seems @hasinhayder has already pushed a request for group wyswiyg issue but you've not merged it yet. So overall please do merge the features & basic one click which will import only contents & theme option nothing else. It would be really helpful. I will also try to contribute. Just let me know how to contribute.
