### ISSUE TITLE
Is there any way of repeating a text field?

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#327]
I saw this feature on some frameworks and also Route WP theme written by @Codestar. Is there a specific way inside csframework or should be done by jquery?

**Comment by Codestar** [comment]
We are using group field for repeating a text?

**Comment by cansanet** [comment]
Would you mind showing a peace of example, I couldnt find in docs.

**Comment by NoahjChampion** [comment]
@cansanet you should search `group` field as @Codestar mentioned, not `repeat...`

See http://codestarframework.com/documentation/#group

Also, like I do... if you're developing you can download/use the demo config files and refer to them because most things you want to do are in the demo config files. 

For example, see the demo group field which allow repeat @ https://github.com/Codestar/codestar-framework/blob/master/config/framework.config.php#L1008-L1135

It is pretty simple, you just put your filed `arrays` in a group `fields => array()`.

```php
// ----------------------------------------------
// begin: group repeater field options
// ----------------------------------------------
array(
    'name'      => 'group_options',
    'title'     => 'Group',
    'icon'      => 'fa fa-check',
    'fields'    => array(
        // Start your group field
        array(
	        'id'              => 'unique_group_1',
	        'type'            => 'group', // <= group field
	        'title'           => 'Group Field',
	        'button_title'    => 'Add New', // Your repeater button text
	        'accordion_title' => 'Add New Field',
	        'fields'          => array(
	            // Start your field options
	            array(
		            'id'          => 'unique_group_1_text',
		            'type'        => 'text',
		            'title'       => 'Text Field',
	            ),
	            array(
		            'id'          => 'unique_group_1_switcher',
		            'type'        => 'switcher',
		            'title'       => 'Switcher Field',
	            ),
	            array(
		            'id'          => 'unique_group_1_textarea',
		            'type'        => 'textarea',
		            'title'       => 'Upload Field',
	            ) // End your field options
        	)
    	) // End your group field
    )
)
```

Also see these articles for help on output... 

[How to output group and post meta value . #253](https://github.com/Codestar/codestar-framework/issues/253)

[How to get the value from a repeater group field #242](https://github.com/Codestar/codestar-framework/issues/242)

Does this satisfy?

**Comment by cansanet** [comment]
Thanks @NoahjChampion 
I think I must re-read documentation.
Now I feel myself like blind.
Thanks again

**Comment by NoahjChampion** [comment]
@cansanet 

No problem. You can always search the Codestar repo like I do... most answer are already there so you don't have to wait for a response. See screenshot if you don't know. I think it is easier than reading documentation. I've already read all Github issues here, which helped me a lot.

<img src="https://monosnap.com/file/QyMFpiD6WknmDOkeGq9qk08XphwjEE.png">

**Comment by Codestar** [comment]
@NoahjChampion thanks for explain :+1:

**Comment by cansanet** [comment]
Thank you @NoahjChampion

**Comment by cansanet** [comment]
Now I under

**Comment by samjco** [comment]
Group field should be renamed Repeatable Fields
