### ISSUE TITLE
Theme Customizer Live Preview

### ISSUE THREAD

**Issue by mandava** [Codestar/codestar-framework#34]
Any plans on adding live preview JS for Theme Customizer options?

**Comment by Codestar** [comment]
Can you explain it more? What mean "Live preview JS" ? If i understand right, you need to create your customizer by yourself, because framework can not find your site elements. Take a look WordPress Core Theme Customization API:

1. [Generating Live CSS](http://codex.wordpress.org/Theme_Customization_API#Part_2:_Generating_Live_CSS)
2. [Configure Live Preview](http://codex.wordpress.org/Theme_Customization_API#Part_3:_Configure_Live_Preview_.28Optional.29)

**Comment by Codestar** [comment]
BTW, [Configure Live Preview - Step 2: Create a JavaScript File](http://codex.wordpress.org/Theme_Customization_API#Step_2:_Create_a_JavaScript_File) Below i am showing what is the a setting id. 

```
$options[]        = array(
  'name'          => 'core_fields',
  'title'         => 'Core Fields',
  'settings'      => array(

    // core text
    array(
      'name'      => 'text_option', // YOUR_SETTING_ID
      'control'   => array(
        'label'   => 'Text Field',
        'type'    => 'text',
      ),
    ),
...
...
```

```
wp.customize( 'YOUR_SETTING_ID', function( value ) {
	value.bind( function( newval ) {
		//Do stuff (newval variable contains your "new" setting data)
	} );
} );
```
