### ISSUE TITLE
Wrong behaviour on switcher

### ISSUE THREAD

**Issue by MichaelSmi** [Codestar/codestar-framework#371]
**Issue:** If you set the default value of a switcher element to true it always displays the switcher as "on/true". This is not intuitive.

This is the code example causing the missbehaviour.
`array(
                'id'          => 'prefix_switcher',
                'type'        => 'switcher',
                'title'       => 'Title here',
                'label' => __( 'Using thissetting.', 'text-domain' ),
                'default'    => true,
                'multilang'=> 'true',
            ),`

Note: I love your framework very much!! It won competition against all the others out there. If my Plugin is successfull I will support your development as your framework is a big fundamental feature of my plugin ;)

**Comment by NoahjChampion** [comment]
@MichaelSmi 

Thanks for loving @Codestar Framework :)

I see what you are saying is not intuitive but I think it is intuitive unless I am misunderstanding what you mean. Let me know. Is this not intuitive or what you mean? 

**Case 1:**
***

```php
array(
    'id' => 'prefix_switcher',
    'type' => 'switcher',
    'title' => 'Title here',
    'label' => __( 'Using this setting.', 'text-domain' ),
    'default' => true,
    'multilang'=> 'true',
),
```
Makes the switcher display "ON" because it is going to be ON by default, right?

**Output:**
***

![image](https://cloud.githubusercontent.com/assets/6123260/17086128/56c0cdb0-51b8-11e6-8cf8-d6fc8d12b319.png)

**Case 2:**
***
```php
array(
    'id' => 'prefix_switcher',
    'type' => 'switcher',
    'title' => 'Title here',
    'label' => __( 'Using this setting.', 'text-domain' ),
    'default' => false,
    'multilang'=> 'true',
),
```
Makes the switcher display "OFF" because the value is going to be OFF by default, right?

**Output:**
***
![image](https://cloud.githubusercontent.com/assets/6123260/17086137/7a0ba470-51b8-11e6-81ae-308aa2d0f0cb.png)

**Comment by NoahjChampion** [comment]
@MichaelSmi 

Hi. I see what you mean now. I actually mentioned this issue kind of awhile ago, not knowing. 

You can try working with this if it fits your need for now. 
_(not ideal, but workable for now)_

You could do a check for the value then force the output of that value

```php
// Force a value to true or false on page load regardless of saved or default value
if(!function_exists('_cs_validate_save')) {
	add_filter('cs_validate_save', '_cs_validate_save');
	function _cs_validate_save($request) {
		// Text
		$request['prefix_switcher'] = true;
		return $request;
	}
}
```

**Reference:**
@ #265

**Comment by Codestar** [comment]
Great answer @NoahjChampion
