### ISSUE TITLE
Theme options page loading time

### ISSUE THREAD

**Issue by pn1gh2** [Codestar/codestar-framework#401]
Are there any ways or tweaks to load theme options page faster? 
There are about 25 options in my theme options. It takes about 7-8 seconds to load completely.

Thanks!

**Comment by NoahjChampion** [comment]
@pn1gh2 

If it is taken that long to load with ONLY 25 options, you have to be using Chosen Jquery for select and multi-select options? Are you?

There is no way so far that I know of around Jquery loading slow when having to convert selects and multi-selects to class "chosen". 

But also, something else should be wrong that is slowing down your setup. The Codestar Demo has many, many, many more options than 25 and has never taken that long to load for me. 

The slowest things loaded for me is when I loaded Google Fonts and Chosen multiple times on one page and that only took 3-4 seconds to load. Never 7-8 seconds. I also have like 200-300 options for my theme and it only takes a few seconds at most to ever load but usually maybe 2 seconds. 

Sooo :) I think this may be something else. So I ask first are you loading the `'type' => 'chosen'` for most things?

**Comment by pn1gh2** [comment]
Thank you very much for reply Noah. You are always here. I do APPRECIATE your time.

Noted for "chosen" jQuery.

But I only have two options for "select" type and no Google Fonts fields.

And yes, Codestar Demo has many options and it only takes 2-3 seconds to load. BTW, I use countdown timer from my phone to check load time. :)

Sorry for (term) confusing between "25 options" and "25 fields". Actually, I have 25 FIELDS in my theme options.  Each field includes 7 types. So there will be around 170-180 option types in theme option.

I find out that "background" type is culprit for part of slow loading. After removing 17 "background" types, my theme option page loads faster. 

But still, it takes a little bit over 6 seconds.

**Comment by NoahjChampion** [comment]
@pn1gh2 you can send/email me your config and I can take a look on my server. 

Still, even with that many options I don't think your site should take 6-7 seconds to load. I've had around this many options and still the admin page only took 3 seconds to load at max and that was because of the Google Fonts with chosen. When I removed them my page still only took 1-2 seconds. I think it is something else or something specific that is loading that CF might be having performance issues with. 

Also a phone countdown timer isn't the proper way to count the load time :) 
There are tools in the browser itself that count the load time for devs to look at. So I can take a look if you would like. Let me know and I shoot my email address.

**Comment by pn1gh2** [comment]
Hey Noah @NoahjChampion 

After tedious and boring trials and errors, I found out why my option page load time took around 7 seconds. All because of "group" type in framework. I use it (group type) to create buttons and contents for home page sections for front end. 

When I get rid of all "group" type - that would be 26 in total (unusual amount) :) - from framework.config, and yes __ my options page load time is going back to 2-3 seconds.

I have very limited skill but don't want to give up Codestar Framework. It's the best and greatest one. I always appreciate the author @Codestar and you - @NoahjChampion for patience and support.

I only slept three hours last night. Feel very good after I find solution!

**Comment by pn1gh2** [comment]
Oh, thank you for real way - using "Network" tab from developer tool. 
Funny + little bit of embarrassed - I used phone countdown timer to check loading time. ;)

Ha Ha Ha

**Comment by NoahjChampion** [comment]
@pn1gh2 

No problem, haha. We all miss something along the way, that's what people are (supposed) to be for. Collectively we can all help everything be better 💯 

I wouldn't know about it unless I looked into site performance, and so I expect others the same as well, since it is performance related. 

And no problem, glad you figured it out. :) 

Yeah, 26 is a unique case and no you know a limit of the web in general, not necessarily the framework. Some things we just can't do or do too much of on one page. 

But if you don't find a solution, someone or me might have another way of trying to implement what you're trying to do. This is how I learned, trial and error but I like it that way because it has caused me to "think outside of the normal" which I think has made me better as a person and as a developer. I'm learning [OOP](http://php.net/manual/en/language.oop5.php) now!!! I think it is AWESOME!!! Lol.

When I saw [OOP](http://php.net/manual/en/language.oop5.php) is basically like dynamic templates for Wordpress pages, content, etc. I got into it. It makes code easier to write and update  from one place for things using that code template/function, etc. <3 :) 👍 

Cheers and you're welcome for the help and @Codevz !!!

I would stick with the Codestar Framework. He mentioned working on an update for v2 and I hopefully :) I think there will be any better options framework available. Codestar is a Rockstar.
