### ISSUE TITLE
Need help about Gallery option

### ISSUE THREAD

**Issue by sharifmeunus** [Codestar/codestar-framework#417]
Is there anyone can help me to user gallery option? 
 I want to know how to use the gallery option in font-end.

**Comment by NoahjChampion** [comment]
@sharifmeunus 

There possible could be, for cost, because this framework is meant for those who know php well or are starting out and need an easy framework to load their fields for the plugin or theme.

So are you looking ti hire somebody? Or are you asking in general?

If you are learning php and want to learn the gallery option, there should be (I think) several other issues here you can search through and gain an understanding of how to write the code you want. 

Let me know, thanks!

**Comment by sharifmeunus** [comment]
Well, i'm asking in general. i'm learning php.

**Comment by NoahjChampion** [comment]
Hi. Sorry for the late response. 

Oh, ok. For this you should research the repo. There are discussions around this here and online. 

It is a broad topic you can easily learn because it's not the Framework that really creates this, for the framework just helps you create the fields to gather the gallery data. The method of gathering that data and outputting it, is essentially the same.

I've never created a gallery, but I think it would mostly revolve around php's [ForEach{}](http://php.net/manual/en/control-structures.foreach.php) function where something like...

foreach ($selected_image as $image) { your code } would be ran from the gallery or repeater fields with galleries, etc. 

You best bet, which I do quite a bit to learn is look at Wordpress repo plugins or premium plugins that do what you need and get the code ideas from there to start. 

Does that help, as I'm not sure where you are at in your php learning! ? :)
Welcome to the club!!

I learned online, self taught, php and I would recommend a course to help speed things up, but once you get comfortable (which I think a course would make happen quicker) php is pretty easy, especially with Wordpress, for the most part. I'm now at the point where I can code things out without having to check every step along the way. But, I could have much sooner got to this point in my php skills earlier if I had taken some courses, haha. I still might though. Php is a "language" like, English, Spanish, etc. So i would treat it as such. So once you know it or the basic things you can easily start to see how to code or what the code is saying because you know what Php is speaking in a sense.
