### ISSUE TITLE
Dependence between metabox.

### ISSUE THREAD

**Issue by Lder** [Codestar/codestar-framework#418]
It is possible to create dependencies between diferente options panels with ( contexts ) diferentes?

eg:  
http://www.awesomescreenshot.com/image/1794786/92c643fb5b2c7055e1c1c14e193e3b68

**Comment by NoahjChampion** [comment]
Hi @Lder 

No it is not (within the framework itself, right now). You have to write some javascript for this to be shown in realtime. 

But here are some articles/solutions.

1. Show the metabox based on Page Template chosen
@ https://paulund.co.uk/display-post-meta-box-specific-page-templates

2. You could by this plugin, maybe look at the code.
@ https://metabox.io/plugins/meta-box-show-hide/

3. But why not just tie those metaboxes together and make fields you want conditionally show from the CF Framework itself? For UX, I think this is best so that the user doesn't have to look for the other metabox after selecting an option somewhere else. 
Example @ 
<img src="https://metabox.io/wp-content/uploads/2015/06/conditional-logic.gif">

4. You can search online as I did find how to do this with javascript at some point before, but right now I'm not finding it in search easily. But it's out there. I've seen it many times. I believe it was on the StackOverflow site or Wordpress Stack site. 

5. This is a good idea though. It can maybe be something for Version 2.
