### ISSUE TITLE
Not issue: Codestar 2.0 Release Date? New Theme?

### ISSUE THREAD

**Issue by pn1gh2** [Codestar/codestar-framework#425]
Hi @Codestar 

Greetings!

As said above, it's not an issue. I am really exciting to see Codestar 2.0 update. May I know release date? :) 

Love your Route theme at TF. Any new themes in near future?

Please consider to monetize Codestar Framework. I want it to live long - forever.

**Comment by Codestar** [comment]
Hi @pn1gh2 

Thanks for your nice opinions. I am working on a new theme for ThemeForest. i will release it future :)

Actually Codestar Framework v2 is almost done, also i shared it for some authors here for beta test. I am planing to update from v1 to v2 but i do not want to get a lot of questions before release my theme. because you know, i am spending a lot of time for answers...

Do you want to see v2, please leave an email via routewp[at]gmail[dot]com

Regards, Codestar
