### ISSUE TITLE
Icon Field

### ISSUE THREAD

**Issue by creativesolvers** [Codestar/codestar-framework#45]
This is just a minor issue, but I was checking the icon field in a local development environment and found out that the icons are correctly load, but do not always display correctly. 

Posible Solution: 
I fixed it by adding 'fa fa-' to the i element in functions/actions.php:23 and the same to fields/icon/icon.php:24. 

Secondly, i added 'fa fa-'+ to assets/js/cs-framework.js:503, changing it to:
$parent.find('i').removeAttr('class').addClass('fa fa-' + icon);

**Comment by Codestar** [comment]
Thanks for report, but i did not understand issue, can you explain it more? you can not add "fa fa-" manually. because icon field also support another icon fonts, not only for font-awesome..

btw, a user was started a topic #26 about this subject. take a look it. and i had made an update for this. maybe you are using older files? can you update files and try it again ?

**Comment by Codestar** [comment]
It is ok now :question:

**Comment by creativesolvers** [comment]
Thanks, I have overlooked the issue, as my json was not updated properly. I will not shave more of your time :).

**Comment by Codestar** [comment]
You're welcome :+1:
