### ISSUE TITLE
How do I display the Metabox Upload Button?

### ISSUE THREAD

**Issue by pinethemes** [Codestar/codestar-framework#513]
Hi, I want to show and display the link of the image that I uploaded as you see it visually, but I could not do this with the code in the table. I could not do this kind of thing.
http://prntscr.com/gyb1h9

I could not do it with this code.
$meta_data = get_post_meta( THE_POST_ID, '_custom_meta_options', true );

Here's the id number of my element.
http://prntscr.com/gyb26l

Could you give me a code that I can directly download the image link I uploaded? Thank you from now.

**Comment by Codestar** [comment]
You need this or i did not understand question ?

```php
$meta_data  = get_post_meta( get_the_ID(), '_custom_post_options', true );

if( $meta_data['home_post_image'] ) {
  echo '<img src="'. $meta_data['home_post_image'] .'" alt="" />';
}
```

**Comment by pinethemes** [comment]
I want to do something like this. If you do not upload an image in the metabox upload area, I want you to automatically show the post thumbnail. How else can I do it with else. If "home_post_image" is empty, show thumbnail. If it is not empty, show "home_post_image". What can I do for it?

**Comment by Codestar** [comment]
Yes it is possible and i updated the code. take a look it.

**Comment by pinethemes** [comment]
unfortunately he gave such an error.
http://prntscr.com/h4m7vq

**Comment by NoahjChampion** [comment]
@pinethemes 

About your error. Please read and check the error. It has information in it telling you about the issue. 

![image](https://user-images.githubusercontent.com/6123260/32275281-05155872-bee1-11e7-9a4c-c250ef7a0bdb.png)

Somewhere in your template you've placed the code wrong breaking the flow of PHP because of the unexpected `;` This means there is a PHP character (open or closing) missing before `;`. This means PHP needs to close an operation out before running your `;`. 

**Check line 54. in your index.php** :D 

Here is an update to his code. It seems wrong function was called by mistake. 

`has_thumbnail()` should be `has_post_thumbnail()`

Reference: https://developer.wordpress.org/reference/functions/has_post_thumbnail/
For the last operation reference: https://developer.wordpress.org/reference/functions/the_post_thumbnail/

```php
// Set our $meta_data variable

$meta_data = get_post_meta(get_the_ID(), '_custom_post_options', TRUE);

// If our $meta_data home_post_image is not empty

if (!empty($meta_data['home_post_image'])) {
	
	// Echo our user's home_post_image
	
	echo '<img src="'. $meta_data['home_post_image'] .'" alt="" />';
	
}

// If our $meta_data home_post_image is empty
//  and if our has_post_thumbnail() function returns TRUE

elseif (has_post_thumbnail()) {
	
	// Echo our user's chosen thumbnail image
	
	echo get_the_post_thumbnail(get_the_ID(), 'thumbnail');

}
```
