### ISSUE TITLE
ThemeForest Issue with CodeStar framework

### ISSUE THREAD

**Issue by Khaled56** [Codestar/codestar-framework#530]
I got a soft rejection with CodeStar Framework for my ThemeForest WordPress Theme. I needed Your help to fix this. Please, help me. I run ns-theme-check plugin and got same error in some lines.

invxtassy/inc/cs-framework/cs-framework-path.php

**409	ERROR	Overriding WordPress globals is prohibited**
413	ERROR	Overriding WordPress globals is prohibited
423	ERROR	Overriding WordPress globals is prohibited
431	ERROR	Overriding WordPress globals is prohibited
437	ERROR	Overriding WordPress globals is prohibited

**Review My Code Please:**

/**
 *
 * Get locate for load textdomain
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
if ( ! function_exists( 'cs_get_locale' ) ) {
  function cs_get_locale() {

    global $locale, $wp_local_package;

    if ( isset( $locale ) ) {
      return apply_filters( 'locale', $locale );
    }

    if ( isset( $wp_local_package ) ) {
      **$locale = $wp_local_package;**
    }

    if ( defined( 'WPLANG' ) ) {
      **$locale = WPLANG;**
    }

    if ( is_multisite() ) {

      if ( defined( 'WP_INSTALLING' ) || ( false === $ms_locale = get_option( 'WPLANG' ) ) ) {
        $ms_locale = get_site_option( 'WPLANG' );
      }

      if ( $ms_locale !== false ) {
        **$locale = $ms_locale;**
      }

    } else {

      $db_locale = get_option( 'WPLANG' );

      if ( $db_locale !== false ) {
        **$locale = $db_locale;**
      }

    }

    if ( empty( $locale ) ) {
      **$locale = 'en_US';**
    }

    return apply_filters( 'locale', $locale );

  }
}

**Comment by Codestar** [comment]
Hi,

You can remove this function for approval file..

invxtassy/inc/cs-framework/cs-framework-path.php

from line : 391 to 453
```php
L:391/**
 *
 * Get locate for load textdomain
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
if ( ! function_exists( 'cs_get_locale' ) ) {
  function cs_get_locale() {
..
..
..
..
L453: load_textdomain( 'cs-framework', CS_DIR .'/languages/'. cs_get_locale() .'.mo' );
```

It is so important to translate framework string.

Still you want to translate feature.. remove lines said as me and only add this....

```php
load_textdomain( 'cs-framework', CS_DIR .'/languages/'. get_locale() .'.mo' );
```

I advise use this framework as plugin for themeforest. because there will be a lot of issues.. Some reviewer will say to you "esc_html, file_get_contents, base64_encode, include_once, bla bla bla" not allowed.

If you having still issue, leave an email via routewp[at]gmail[dot]com
