### ISSUE TITLE
Codestar framework on theme and plugin

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#545]
Hi,

I am having an issue when we have Codestar framework on theme and plugin both.

My theme has Codestar framework inside. I am using it for theme option, customizer and meta box.

Now I am trying to develop a plugin using Codestar framework. I need its meta box for my plugin.

I tried to add my meta fields using "cs_metabox_options" hook. Which works great. 

Now my problem is, as my theme also using Codestar framework when I install and activate the plugin the theme options page not showing.

I guess the framework looking for the framework config file inside my plugin, which is not available.

My question is, is there any way to use this framework both on theme and plugin. I just want to make sure my plugin is compatible with all the theme developed with Codestar framework.

Thanks

**Comment by samjco** [comment]
You can add this to you plugin and theme on the lines where you are require_once cs_framework.php

Replace this:
```php
require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';
```
with this in your plugin:
```php
if( ! function_exists( 'cs_framework_init' ) && ! class_exists( 'CSFramework' ) ) {
  //For plugin only
  require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';
}
```
And in you theme. Replace this:
```php
require_once get_template_directory() .'/cs-framework/cs-framework.php';
```
with this:
```php
if( ! function_exists( 'cs_framework_init' ) && ! class_exists( 'CSFramework' ) ) {
  //For theme
  require_once get_template_directory() .'/cs-framework/cs-framework.php';
}
```

**Comment by wpbean** [comment]
Hi @samjco,

You may not understand my problem and my question.

I have no error, I already call cs-framework.php file both on my plugin and theme with these conditions. 

My problem is, theme options page for my theme not shows on WordPress admin menu when my plugin is active. 

Thanks

**Comment by samjco** [comment]
How is your each of you frameworks being called?

**Comment by samjco** [comment]
I would assume..
```php
// Plugin
$my_plugin_settings           = array(
  'menu_title'      => 'Plugin Framework',
  'menu_type'       => 'menu', // menu, submenu, options, theme, etc.
  'menu_slug'       => 'my-plugin-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>',
);
```

and theme:
```php
// Theme
$my_plugin_settings           = array(
  'menu_title'      => 'Theme Framework',
  'menu_type'       => 'menu', // menu, submenu, options, theme, etc.
  'menu_slug'       => 'my-theme-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>',
);
```

**Comment by varunsridharan** [comment]
@wpbean @samjco as of now CSFramework Dose not support Multiple Instances.
which means you can just create only 1 settings framework

BTY you can have a look at https://github.com/wpsf/wpsf-dev which is a clone / fork of CSFramework which is more powerful and light weight. 

please do ping me up @ skype for more info : varunsridharan23

also i am not disrespecting @Codestar by providing a fork link in here. he did great job.  i just wanted to have some custom feature and also decided to lunch it publicly thats the reason i am sharing it here.

**Comment by samjco** [comment]
@varunsridharan just curious, why not just support CSF?

**Comment by varunsridharan** [comment]
@samjco 

it seems @Codestar  is too busy and even i tried to contact him many times. asking him that i can be a part of it and manage this . but i never got a proper reply. and also he is buys that it takes more time to merge a pull request. so i decided to make a clone version of it. 

still i have much respect for @Codestar for making this awesome framework.

**Comment by samjco** [comment]
I know @Codestar is off finishing up V2 which for a fact will be more powerful and support multiple instances.. with new fields as well.

**Comment by varunsridharan** [comment]
@samjco i know too. :) again! i also wanted CodeStar V2 :) i am looking for it :)

**Comment by Codestar** [comment]
Hi Guys,

You know, time is big problem for all developers. We need the money for life. I am an author at ThemeForest. I am developing the framework, when i have free-time, progressing slowly. I can not more.

@varunsridharan You did try to contact me. Yes, But you are talking about transfer/manage the project, I can not this. And i don't like your share policy. You are sharing a extended version of framework and writing "**more powerfull and reliable**" And I can not see "**Codestar**" name anywhere. And now you are taking about V2. If i give you V2, maybe you will share V3 and write "more powerfull and reliable" how i can be sure for this ? That is why i do not share v2 with you.

I have different plans for Codestar Framework V2 in the future.

@samjco @Codevz @Ansif @EnterpriseBranding

Regards

**Comment by varunsridharan** [comment]
@Codestar 

I know you would really take it wrong. And i am really sorry please do be offended on this.

Since i have not yet completed fully. 

Yes i did contacted you about the share / merge. but after you said you are working on it. i told you that i am ready to help you anyway i possible could.

But haven't got any proper reply from you..

And also i sent you an email recently 

Email : http://s.svarun.in/kR

Pls note that i asked you that if you would like to merge my source with the updated code.

But haven't got any reply. so i together that you are not interested .

Since i am going to use this in my plugins & theme. so i decided to clone this. on my own. 

Yes i did used your code and i am ready to give it a proper credit once all the things are done.

And in this link (https://github.com/wpsf/wpsf-dev ) i have already mentioned that its (Clone Of CodeStar) 

Still i have a lot of respect for you. i really love the work you. do

**Comment by Codestar** [comment]
@varunsridharan 

I am not so angry, only a little offended... as a result this is a open-source project. Yes, but 2x power framework shared with different name that is unacceptable. You can use 10x powerfull on your projects with different name. It is all ok no problem. Anyway we will see v2 or pro version soon...

Also i respect for your labor too. Ok Let's see what will happen in the future.. If you are right, your repo will popular more than main repo :)

Regards

**Comment by varunsridharan** [comment]
@Codestar 

I am sorry. its was not done on intention.  and also i never wanted WPSF to be popular.
I just shared my work. basically it was done as a private personal project. but then i just wanted to put it public in case if any 1 wants can use it. 

I dont have a website / any thing for it. just a doc site thats supported by GitBooks

As said before. i am ready to merge with CS and even i have more ideas. i am ready to work on that to..

**Comment by Codevz** [comment]
@varunsridharan Sending pull request for adding / improving features is always best way for free projects on GitHub

**Comment by Codestar** [comment]
@varunsridharan 

I understand, Everything is ok. Said as me v2 will take time a little more. Firstly I need to finish my new theme ASAP. =)

Have a nice day.

**Comment by samjco** [comment]
I think that, because of the fact that @Codestar built a wonderful framework already and has freely opened it up to us developers, deserves the respect for us to "stick with it" or "contribute to it".

@varunsridharan 
Why not just commit your changes and ideas here and when CodeStar gets time, he'll get to them. That's what I do. :) And that is how WordPress became WordPress!

**Comment by varunsridharan** [comment]
@Codevz 

Yes you are right and i do follow that way. but in this case its not.

I have already send 2 request 1got merged and other 1 haven't ( https://github.com/Codestar/codestar-framework/pull/488) I know @Codestar  is busy and will merge once he gets free time. 

Due to that only i extended the CS if any 1 feels offended i am really sorry. 

I really respect you guys ( @Codevz @samjco @Codestar ) And your contribution. 

@Codestar Let me know once your are free  i can extract some important feature code and send it to you.  or we both can sit for 2 days and merge WPSF with CS
