### ISSUE TITLE
get taxonomies names by post type

### ISSUE THREAD

**Issue by stivoox** [Codestar/codestar-framework#549]
Hi friends .
how to get the taxonomies names by post type with this framework .
for ex : select box for each taxonomy and taxonomy terms as select options .
regards

**Comment by Codevz** [comment]
For category
```PHP
array(
  'id'             => 'unique_option_512',
  'type'           => 'select',
  'title'          => 'Select Field for CPT Posts',
  'options'        => 'categories',
  'query_args'     => array(
    'type'         => 'movies',
    'taxonomy'     => 'movies_taxonomy',
    'orderby'      => 'post_date',
    'order'        => 'DESC',
  ),
  'default_option' => 'Select a category',
),
```

for tags
```PHP
array(
  'id'             => 'unique_option_513',
  'type'           => 'select',
  'title'          => 'Select Field for CPT Tags',
  'options'        => 'tags',
  'query_args'     => array(
    'taxonomies'   => array( 'post_tag', 'your_tax' ),
    'orderby'      => 'post_date',
    'order'        => 'ASC',
  ),
  'default_option' => 'Select a tag',
),
```

You can find all select features here: http://codestarframework.com/documentation/#select

**Comment by stivoox** [comment]
no that's not what i'm looking for .
I want to generate taxonomy names of a post type and put them in a select box . 
for exemple if we have a post type called 'car' with taxonomie : color , type , .... i want a select box of those taxonomies .

**Comment by Codevz** [comment]
Like this you can get taxonomies list: 

```PHP
$options = array( '' => 'Select' );
$terms = get_terms( 'YOUR_TAXONOMY_NAME' );
if ( ! empty( $terms ) && ! is_wp_error( $terms ) ) {
	foreach ( $terms as $term ) {
		if ( isset( $term->term_id ) ) {
			$options[ $term->term_id ] = $term->name;
		}
	}
}
```

then in select > options param set $options

**Comment by stivoox** [comment]
Sorry , But i want to get taxonomies by post type name . not terms by taxonomies name . 
that's the output that I hope to achieve .
<select>
  <option value="color">Color</option>
  <option value="Type">Type</option>
  <option value="Other taxonomy">Other taxonomy</option>
  <option value="audi">Audi</option>
</select>

**Comment by samjco** [comment]
In order to get the terms that were assigned to a post type you would first have to get the registered taxonomy (e.g category, post_tag, post_format, my_custom_tax). 

https://developer.wordpress.org/reference/functions/get_object_taxonomies/

Once you know which taxonomy you want to target, then you can began to get the terms of that taxonomy. 

This is because multiple terms can be assigned to multiple post types (e.g categories)

What I would do is to try to isolate the taxonomy name desired of a post type by using: 

''<?php 
$args = array(
  'public'   => true,
  '_builtin' => false
  
); 
$output = 'names'; // or objects
$operator = 'and'; // 'and' or 'or'
$taxonomies = get_taxonomies( $args, $output, $operator ); 
if ( $taxonomies ) {
  foreach ( $taxonomies  as $taxonomy ) {
    echo '<p>' . $taxonomy . '</p>';
  }
}
?>''

Perhaps storing the first returned tax into a variable. $taxonomy[0] (if I remember correctly)

And then getting your terms from that. 

''
$terms = get_terms( $taxonomy[0]);
if ( ! empty( $terms ) && ! is_wp_error( $terms ) ) {
	foreach ( $terms as $term ) {
		if ( isset( $term->term_id ) ) {
			$options[ $term->term_id ] = $term->name;
}
}
}
''
