### ISSUE TITLE
Issue with save action

### ISSUE THREAD

**Issue by lahmacun** [Codestar/codestar-framework#71]
Hi, I hope you doing well.

I'm having same issue with #28 . I have fields for Cloudflare. API Key, Zone ID and email address.
I want to display an error message to user if api credentials are incorrect but I can not get my current status without refresh. Also I'm having same issue with my Rocket Loader option.

I fetch rocket loader status just before create section. It fetches the options from remote server and sets the value. After save, I update the option on Cloudflare side but just after the save, I don't see the recent rocket loader status. First it fetches the Rocket Loader status and saves the data.

This is my project: https://github.com/optimocha/speed-booster-pack

You can see the code in `admin/class-speed-booster-pack-admin.php`. Related lines are: `161`, `1006`, `1021`

I'll provide any other information that you need.

Best regards.

**Comment by Codestar** [comment]
Hi,

Thanks everything is good. I hope you same too..

Yes, I understood what you try. There is no option for check any api credentials without refresh.

I have read your code. I want to give some idea.

```
add_action( 'csf_loaded', '\SpeedBooster\SBP_Cloudflare::check_credentials' );
get_transient( 'sbp_cloudflare_status' );
```

I didn't like these idea. If I were you I would add a button like this and use ajax.

| Button    | Correct  | Incorrect |
| ----------- | ----------- | ----------- |
| ![screenshot_ec301e1cd](https://user-images.githubusercontent.com/1313301/92379506-435a8d00-f110-11ea-8414-a9fb1fc2103e.png) | ![screenshot_476c14332](https://user-images.githubusercontent.com/1313301/92379729-99c7cb80-f110-11ea-9758-0cfd6e3f26d9.png) | ![screenshot_3324b4ad6](https://user-images.githubusercontent.com/1313301/92379796-b401a980-f110-11ea-9fdd-1c92d837f0f5.png)

```php
// Field tip.
[
  'type'    => 'content',
  'content' => '
    <a href="#" class="button button-small sbp-cloudflare-test">Test Your Cloudflare Connection</a>
    <span class="sbp-cloudflare-incorrect" style="color:red; vertical-align: middle;"><i class="fa fa-exclamation-triangle"></i> Your Cloudflare credentials are incorrect.</span>
    <span class="sbp-cloudflare-correct" style="color:green; vertical-align: middle;"><i class="fa fa-check-circle"></i> Your Cloudflare credentials are correct.</span>
  ',
],
```

```javascript
// jQuery selector tip.
$('[data-depend-id="cloudflare_api"]').val();
$('[data-depend-id="cloudflare_email"]').val();
$('[data-depend-id="cloudflare_zone"]').val();
```

Regards

**Comment by Codestar** [comment]
@lahmacun @optimocha

A critical thing. I have take a look your code. I don't know how to explain but I'll try.

https://github.com/optimocha/speed-booster-pack/blob/19b4dcb455f732b94eebe10c2eadb80993ebbdd5/includes/class-speed-booster-pack.php#L248

The admin panel creates with this line. Yes, but It works ( queries ) in front -page as well.

For eg. Right now there are 18 queries in front-page by SBP.

![screenshot_d59d7f3b0](https://user-images.githubusercontent.com/1313301/92461600-27b7bb00-f1d2-11ea-99cb-3388292a9ad7.png)

If you run admin panel like this:

```php

if( is_admin() ) {

  $plugin_admin = new Speed_Booster_Pack_Admin( $this->get_plugin_name(), $this->get_version() );

  $this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );
  $this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );

}
```

The results:

![screenshot_41eb1bd69](https://user-images.githubusercontent.com/1313301/92461628-2d150580-f1d2-11ea-9c14-f6c474f41a2c.png)

For eg these queries coming from:

```php
$this->set_notices(); ( 10queries ) // For eg, I think these notices only needed in admin panel area. why it function run in front-page as well ? Do control it with a is_admin()
$this->create_settings_page(); ( 2queries )
// and others...
```

Btw only you should to move **admin_bar_menu** action. because it doesn't work inside **is_admin** condition. Also I didn't check others, take a look all of them.

Regards

**Comment by lahmacun** [comment]
Hi,

Thank you for for your interest and response. I'll fix it ASAP.

Best regards.

**Comment by Codestar** [comment]
You're welcome :+1:
