### ISSUE TITLE
CSF multilanguage problem.

### ISSUE THREAD

**Issue by 0xBeycan** [Codestar/codestar-framework#84]
Hello I have set a multi-language option for my plugin and I used csf for settings, but the language did not change in csf. I tried the admin_init, csf_init and csf_loaded hooks.

'id'    => 'design_settings', 
'title' => lsph__( 'Design options' ),
'icon'   => 'fa fa-palette',
'fields' => array(

// Multi language
add_action( "init", "lsph_multi_language" );
add_action( "csf_loaded", "lsph_multi_language" );
function lsph_multi_language(){
    load_plugin_textdomain( 'lsph', false, LSPH_LANG );
}

**Comment by Codestar** [comment]
Hi,

I didn't get the subject. Can you elaborate further ?

Actually there is no option for multilangual. Simply we are using wpml-config.xml for assign framework options.

Regards

**Comment by 0xBeycan** [comment]
I have a text file for my plugin. I set the CSF settings names with it. The language changes in the menu I added with admin_menu, but the language does not change in CSF. So I change the language with loco translate. The language of the plugin changes, but that of the CSF does not.

**Comment by Codestar** [comment]
Hi,

Hey, send me the your plugin as **lite-version or example code** via routewp[at]gmail[dot]com I need see it detailed. You know it =)

Regards

**Comment by 0xBeycan** [comment]
I sent hello.

**Comment by Codestar** [comment]
Hi,

I examined this issue. Only you should set correct hook priorities. The framework run on **init** action and priority is **10**. So your hooks must be set low than priority 10. Ok anyway let's see it on code.

```php
// lsph/inc/functions.php L165
// from
add_action( "init", "lsph_multi_language" );
// to
add_action( "init", "lsph_multi_language", 9 );
``

```php
// lsph/inc/wp-admin.php L24
// from
require_once LSPH_PATH . 'admin/options.php';
// to
function lsph_options() {
  require_once LSPH_PATH . 'admin/options.php';
}
add_action( 'init', 'lsph_options', 9 );
```

**Note:** "**General options**" looks as "**General Options**" in pot file. you should use same. ( also look for "Design options" )

Finally, update the framework because I have added a lot of languages for common strings https://github.com/Codestar/codestar-framework/tree/master/languages

Regards

**Comment by 0xBeycan** [comment]
Hello I updated the framework and fulfilled what you said but still no change. You can see in the pictures below, I could not find any answer to this. Does this product accept envato? If not, why not, could I use CSF be a reason for refusal? Also, do you have any suggestions that I didn't need to use OOP because it is not a very large software?

https://prnt.sc/vo9dtg

https://prnt.sc/vo9e0d

https://prnt.sc/vo9e6q

**Comment by BeycanDeveloper** [comment]
Hello I updated the framework and fulfilled what you said but still no change. You can see in the pictures below, I could not find any answer to this. Does this product accept envato? If not, why not, could I use CSF be a reason for refusal? Also, do you have any suggestions that I didn't need to use OOP because it is not a very large software?

**Comment by BeycanDeveloper** [comment]
Hello I updated the framework and fulfilled what you said but still no change. You can see in the pictures below, I could not find any answer to this. Does this product accept envato? If not, why not, could I use CSF be a reason for refusal? Also, do you have any suggestions that I didn't need to use OOP because it is not a very large software?

https://prnt.sc/vo9g6n
https://prnt.sc/vo9gbt
https://prnt.sc/vo9ggp

**Comment by 0xBeycan** [comment]
I have set up this structure for easy use. I can import the text, but now I noticed that the texts are not going to the .pot file. Which hook should I hook or as esc_html__ or esc_attr__? I have to use it because it's tiring.

https://prnt.sc/vo9r6b

**Comment by Codestar** [comment]
Hi,

I forgot to say, this ( **lsph__** ) usage is not correct, or I can say "I do not advise". Yes the pot file doesn't update because it's not find the correct line.

![image](https://user-images.githubusercontent.com/1313301/99948518-a57b7380-2d8a-11eb-9238-5c4e12857c0f.png)

As you see, it references line 366, but it not located there. I think you created pot file before convert **esc_html__** to **lsph__**. Leave **lsph__** idea.  What is the correct way:

```php
// from
lsph__( 'LSPH Panel' )
// to
esc_html__( 'LSPH Panel', 'lsph' )
```

convert everything and re-scan and create new pot file ( you can use loco translate for create pot ).

Regards

**Comment by 0xBeycan** [comment]
Thank you I will replace and test and write.

**Comment by 0xBeycan** [comment]
Hello, I updated lsph__ to esc_html__ or esc_attr__, and then the plugin language changed again, but CSF remained the same.

https://prnt.sc/vob9z0
https://prnt.sc/voba7l
https://prnt.sc/vobadh
https://prnt.sc/vobaxo

**Comment by Codestar** [comment]
Hi,

Can you update this and try again ?

```php
// lsph/inc/functions.php L165
// from
add_action( "init", "lsph_multi_language", 9 );
// to
add_action( "init", "lsph_multi_language", 8 );
```

Regards

**Comment by 0xBeycan** [comment]
Hello, thanks. I did the opposite. I tried 8 for lsph_options I guess I need to work on these sorting events a little more.

**Comment by Codestar** [comment]
Yes, I am confused too. :)) Notice me for latest changes. May someones need same thing.

**Comment by 0xBeycan** [comment]
It works fine when hooking "init" in this way.

`
function lsph_options() {
        require_once LSPH_PATH . 'inc/options.php';
}
add_action( 'init', 'lsph_options', 9 );

add_action( "init", "lsph_multi_language", 8 );
function lsph_multi_language(){
    load_plugin_textdomain( 'lsph', false, LSPH_LANG );
}
`

**Comment by Codestar** [comment]
Nice. whats happened **lsph__** vs **esc_html__** ? which one you use ?

**Comment by 0xBeycan** [comment]
lsph__ did not work but now I am using esc_html__ or esc_attr__ so I will search this again another time.

**Comment by Codestar** [comment]
Yea good :+1:
