### ISSUE TITLE
Error! Can not load json file.

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#85]
typography field says Error! Can not load json file.!!

**Comment by devariya** [comment]
solved

**Comment by Codestar** [comment]
Hi @devariya 

Actually, i need an idea for this issue. i will try to explain. take a look #44 i was using php core function ```file_get_contents``` but this is getting theme-check plugin warning. theme-check advising ```WP_Filesystem``` and i used what advising theme-check. but wordpress core function ```WP_Filesystem``` can not load json file sometimes because this function checking permissions. also take a look here http://wordpress.stackexchange.com/questions/166161/why-cant-the-wp-filesystem-api-read-googlefonts-json you will understand easy.

Shortly, what we need to use ? ```file_get_contents``` or ```WP_Filesystem``` ? what you think. let's ignore theme-check ?

**Comment by devariya** [comment]
I think Ignore theme-check not a good idea at all ,Maybe now we need to give custom support when client/buyer face this issue .

**Comment by Codestar** [comment]
Oke, i am thinking to change it now. btw how to you solve it ?

**Comment by devariya** [comment]
i am using <code>wp_remote_retrieve_body</code> for json file

**Comment by Codestar** [comment]
```php
// no:1
$google_json   = json_decode( wp_remote_retrieve_body( wp_remote_get( CS_URI .'/fields/typography/google-fonts.json' ) ) );
```

```php
// no:2
$google_json   = json_decode( wp_remote_fopen( CS_URI .'/fields/typography/google-fonts.json' ) );
```

```php
// no:3
$google_json   = json_decode( file_get_contents( CS_URI .'/fields/typography/google-fonts.json' ) );
```

I am planing to no:2, can you check it, will work on your system ?

**Comment by devariya** [comment]
No2 just working fine .

**Comment by Codestar** [comment]
Ok, let's use it :wink:
