### ISSUE TITLE
Can not open Customizer Page

### ISSUE THREAD

**Issue by ariona** [Codestar/codestar-framework#91]
After installing Codestar Plugin, i can't navigate to Customize page, it showing:

    Fatal error: Class 'WP_Customize_Media_Control' not found in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/codestar-framework-master/classes/customize.class.php on line 145

**Comment by ariona** [comment]
It seem that media control isn't exist? i tried to remove 'media' on line `140` and it's working.

**Comment by Codestar** [comment]
Hi, I just check this class history, and this ```WP_Customize_Media_Control``` class added since 4.2.0 hmm if so, i think you are using older version < 4.2.0 ?

btw, ( if you do not want to update wordpress version ) this class triggering when use ```media``` customize option field. you can remove this config :wink: 

```
// media
array(
  'name'    => 'media_option',
  'control' => array(
    'label' => 'Media',
    'type'  => 'media', // do not use this. remove it from config file.
  ),
),
```

also i will add a checker for class exists in next updates :+1:

**Comment by ariona** [comment]
Oh my, thanks for the head up, I still used 4.1.1. Updated the WordPress version and it's working now.

And yeah you should add checker for it 👍

**Comment by Codestar** [comment]
You're welcome :+1:  added checker on dev branch :wink:
